services:
  movie:
    build: ./movie
    ports:
      - "3200:3200" 
    environment:
      - USE_MONGO=true
      - MONGO_URL=mongodb://mongo:27017/archiDistriDB
      - USE_DOCKER=true
    depends_on:
      - mongo
    restart: unless-stopped

  user:
    build: ./user
    ports:
      - "3203:3203"
    environment:
      - USE_MONGO=true
      - MONGO_URL=mongodb://mongo:27017/archiDistriDB
      - USE_DOCKER=true
    depends_on:
      - mongo
    restart: unless-stopped

  booking:
    build: ./booking
    ports:
      - "3001:3001"
    environment:
      - USE_MONGO=true
      - MONGO_URL=mongodb://mongo:27017/archiDistriDB
      - USE_DOCKER=true
    depends_on:
      - mongo
    restart: unless-stopped

  schedule:
    build: ./schedule
    ports:
      - "50051:50051" 
    environment:
      - USE_MONGO=true
      - MONGO_URL=mongodb://mongo:27017/archiDistriDB
      - USE_DOCKER=true
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=archiDistriDB

volumes:
  mongo_data:
